[package]
name = "gen_voronoi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
euclid = "0.22.9"
num-rational = "0.4.1"
rand_chacha = "0.3.1"
rand = "0.8.5"